### ISSUE TITLE
Configuration of how and when to delete

### ISSUE THREAD

**Issue by sondr3** [nais/babylon#11]
- [x] Put options into `nais.yml` 
  - [x] Update `liberator`
  - [x] Figure out what to do :shipit: 
- [x] Document what options and what they do
- [x] Which options are relevant for overriding?
  - disable pruning by babylon 
  - disable rollbacks
  - turn of deploy instead of rolling back
 
 more proposals 
 - configure resource age/notification timeout/restart threshold
 - ++

Use a different name than `babylon` in the spec, suggestion for `disableCleanUp`

**Comment by sechmann** [comment]
```
spec:
  cleanup:
    enabled: true
    rollback: true
    gracePeriod: 24h
```
